name: Release
on:
  workflow_dispatch:
    inputs:
      version_name:
        description: 'The version name to release. E.g. 24.12.31'
        required: false
        default: null
      version_code:
        description: 'The version code (numeric) to release. E.g. 241231'
        required: false
        default: null

env:
  IS_AUTO_CI_RELEASE: false

jobs:
  empower-plant-release:
    runs-on: macos-13
    name: 'Release a new Android Empower Plant version'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java Version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Enable auto CI release
        if: inputs.version_name == null
        run: echo "IS_AUTO_CI_RELEASE=true" >> $GITHUB_ENV

      - name: Run Deploy Script
        run: ./deploy_project.sh ${{ inputs.version_name || $(date +'%y.%m.%d') }}
        shell: sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VERSION_NAME: ${{ inputs.version_name || $(date +'%y.%m.%d') }}
          VERSION_CODE: ${{ inputs.version_code || $(date +'%y%m%d') }}

